Fixed an inconsistent treatment of vsys
jinshisai/SLAM pull request #24
Opened 2022-11-17 11:23 UTC by jinshisai

- Vsys output on the terminal is now in the absolute value
- Fix a few lines so that Vsys shown on the terminal and in popt is consistent.
- _pvfit_vcut.pdf (_xcut.pdf) --> .pvfit.vcut.png (.xcut.png) (sorted the format to match other files)

2022-11-17 11:33 UTC, yusukeaso-astron commented on pvanalysis/_pvanalysis.py
>              self.avevsys = 0
self.vsys_opt is not defined in the case of "else". So, self.avevsys = 0 --> self.vsys_opt = self.vsys?

2022-11-17 11:36 UTC, yusukeaso-astron commented on example.py
> +include_vsys = True  # vsys offset. False means vsys=0.
Do we need to change example.py?

2022-11-17 11:40 UTC, yusukeaso-astron commented on pvanalysis/_pvanalysis.py
> +            popt[4] -= self.avevsys
If self.vsys_opt is defined in any case, popt[4] -= self.avevsys --> popt[4] = self.vsys_opt?

2022-11-17 12:52 UTC, yusukeaso-astron commented on example.py
> +show_corner = False  # figures will be made regardless of this option.
Here is another change.

2022-11-17 12:58 UTC, yusukeaso-astron requested changes

2022-11-17 12:58 UTC, yusukeaso-astron commented on example.py
> +show_corner = False  # figures will be made regardless of this option.
show_corner = True

2022-11-18 04:43 UTC, jinshisai commented on example.py
> +show_corner = False  # figures will be made regardless of this option.
Solved now

2022-11-18 05:01 UTC, merged